from django.core.management.base import BaseCommand
from tracker.models import Team, UserProfile, Activity, Workout, LeaderboardEntry
from django.utils import timezone
import random
from django.conf import settings
from pymongo import MongoClient


class Command(BaseCommand):
    help = 'Populate the octofit_db database with test data'

    def handle(self, *args, **options):
        self.stdout.write('Starting population of octofit_db...')

        # Clear existing data using Django ORM
        LeaderboardEntry.objects.all().delete()
        Activity.objects.all().delete()
        Workout.objects.all().delete()
        UserProfile.objects.all().delete()
        Team.objects.all().delete()

        # Create teams
        marvel = Team.objects.create(name='marvel')
        dc = Team.objects.create(name='dc')

        # Sample superhero users
        marvel_heroes = [
            ('Iron Man', 'tony@stark.example'),
            ('Captain America', 'steve@rogers.example'),
            ('Black Widow', 'natasha@romanoff.example'),
        ]
        dc_heroes = [
            ('Superman', 'clark@kent.example'),
            ('Batman', 'bruce@wayne.example'),
            ('Wonder Woman', 'diana@prince.example'),
        ]

        users = []
        for name, email in marvel_heroes:
            u = UserProfile.objects.create(name=name, email=email, team=marvel)
            users.append(u)

        for name, email in dc_heroes:
            u = UserProfile.objects.create(name=name, email=email, team=dc)
            users.append(u)

        # Create activities and workouts
        activity_types = ['run', 'bike', 'swim', 'yoga', 'lift']
        for user in users:
            for i in range(2):
                Activity.objects.create(
                    user=user,
                    activity_type=random.choice(activity_types),
                    duration_minutes=random.randint(20, 90),
                    calories=random.randint(100, 800),
                )
                Workout.objects.create(
                    user=user,
                    title=f"Workout {i+1} for {user.name}",
                    description='Autogenerated sample workout',
                    duration_minutes=random.randint(15, 75),
                )

        # Leaderboard entries
        for user in users:
            LeaderboardEntry.objects.create(user=user, points=random.randint(0, 1000))

        # Ensure unique index on user email via pymongo
        db_name = settings.DATABASES['default'].get('NAME', 'octofit_db')
        client_kwargs = {}
        client_info = settings.DATABASES['default'].get('CLIENT', {})
        host = client_info.get('host', 'localhost')
        port = client_info.get('port', 27017)
        client = MongoClient(host=host, port=port, **client_kwargs)

        db = client[db_name]
        # Determine collection name for UserProfile model
        collection_name = UserProfile._meta.db_table
        self.stdout.write(f'Ensuring unique index on {collection_name}.email')
        try:
            db[collection_name].create_index([('email', 1)], unique=True)
            self.stdout.write('Unique index created or already exists.')
        except Exception as e:
            self.stderr.write(f'Failed to create unique index: {e}')

        self.stdout.write('Database population complete.')